service: merge-lock-user-service

provider:
  profile: ml-serverless
  name: aws
  runtime: python2.7
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Scan"
        - "dynamodb:Query"


functions:
  update:
    handler: handler.update
    events:
      - http:
          path: user-service/user
          method: PUT
          
  listAll:
    handler: handler.list_all
    events:
      - http:
          path: user-service/user
          method: GET
  
  list:
    handler: handler.list
    events:
      - http:
          path: user-service/user/{username}
          method: GET

  reverseList:
    handler: handler.reverseList
    events:
      - http:
          path: user-service/user/reverse/{username}
          method: GET
  
  delete:
    handler: handler.delete
    events:
      - http:
          path: user-service/user/{username}
          method: DELETE

resources:
  Resources:
    userEventsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'users'


