service: slack-merge-lock-service

provider:
  profile: ml-serverless
  name: aws
  runtime: python2.7
  stage: dev
  region: eu-west-1
  # TODO Remove
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"

functions:
  mergeLock:
    handler: handler.merge_lock
    events:
      - http:
          path: slack/merge-lock
          method: post
          integration: lambda
  # TODO remove
  dispatcherResponses:
    handler: handler.dispatcher_responses
    events:
      - sns: listQueueResponse
      - sns: addResponse
      - sns: removeResponse