service: slack-merge-lock-service

provider:
  profile: ml-serverless
  name: aws
  runtime: python2.7
  stage: dev
  region: eu-west-1
custom:
  writeEnvVars:
    STAGE: ${opt:stage}

plugins:
  - serverless-plugin-write-env-vars
functions:
  mergeLock:
    handler: handler.merge_lock
    events:
      - http:
          path: slack/merge-lock
          method: post
          integration: lambda