service: slack-merge-lock-service

provider:
  profile: ml-serverless
  name: aws
  runtime: python2.7
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "lambda:*"

package:
  include:
    - ../commons/**

custom:
  writeEnvVars:
    REGION: ${opt:region}
    STAGE: ${opt:stage}
    DEV_USER_SERVICE_API_ID: ${file(../env_vars.yml):DEV_USER_SERVICE_API_ID}
    DEV_QUEUE_SERVICE_API_ID: ${file(../env_vars.yml):DEV_QUEUE_SERVICE_API_ID}
    DEV_STATUS_SERVICE_API_ID: ${file(../env_vars.yml):DEV_STATUS_SERVICE_API_ID}

    PROD_USER_SERVICE_API_ID: ${file(../env_vars.yml):PROD_USER_SERVICE_API_ID}
    PROD_QUEUE_SERVICE_API_ID: ${file(../env_vars.yml):PROD_QUEUE_SERVICE_API_ID}
    PROD_STATUS_SERVICE_API_ID: ${file(../env_vars.yml):PROD_STATUS_SERVICE_API_ID}
    
    REPLIER_LAMBDA_NAME: ${self:service}-${opt:stage}-functionDispatcher

plugins:
  - serverless-plugin-write-env-vars
functions:
  functionMergeLock:
    handler: handler.merge_lock
    events:
      - http:
          path: slack/merge-lock
          method: post
          integration: lambda

  functionDispatcher:
    handler: handler.dispatcher