service: slack-merge-lock-service

provider:
  profile: ml-serverless
  name: aws
  runtime: python2.7
  stage: dev
  region: eu-west-1
custom:
  writeEnvVars:
    STAGE: ${opt:stage}
    DEV_USER_SERVICE_API_ID: ${file(../env_vars.yml):DEV_USER_SERVICE_API_ID}
    DEV_QUEUE_SERVICE_API_ID: ${file(../env_vars.yml):DEV_QUEUE_SERVICE_API_ID}

    PROD_USER_SERVICE_API_ID: ${file(../env_vars.yml):PROD_USER_SERVICE_API_ID}
    PROD_QUEUE_SERVICE_API_ID: ${file(../env_vars.yml):PROD_QUEUE_SERVICE_API_ID}

plugins:
  - serverless-plugin-write-env-vars
functions:
  mergeLock:
    handler: handler.merge_lock
    events:
      - http:
          path: slack/merge-lock
          method: post
          integration: lambda