service: slack-merge-lock-service

provider:
  profile: ml-serverless
  name: aws
  runtime: python2.7
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "dynamodb:*"
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"

functions:
  # dispatcher:
  #   handler: handler.dispatcher
  #   events:
  #     #TODO: Find the way to make this dynamic
  #     - stream: arn:aws:dynamodb:eu-west-1:015754386147:table/events/stream/2016-10-23T17:25:21.442
  #     - sns: dispatch
  mergeLock:
    handler: handler.merge_lock
    events:
      - http:
          path: slack/merge-lock
          method: post
          integration: lambda