service: merge-lock-notification-service

provider:
  profile: ml-serverless
  name: aws
  runtime: python2.7
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "lambda:InvokeFunction"

plugins:
  - serverless-plugin-write-env-vars

custom:
  writeEnvVars:
    LAMBDA_NAME: ${self:service}-${opt:stage}-notifySlack


functions:
  notifySlack:
    handler: handler.notify_slack
  userAddedListener:
    handler: handler.user_added_listener
    # events:
    #   - sns: ${opt:stage}-user_added_listener
  newTopListener:
    handler: handler.new_top_listener
    events:
      - sns: ${opt:stage}-new_top_listener
  unauthorizedPushListener:
    handler: handler.unauthorized_push_listener
    events:
      - sns: ${opt:stage}-unauthorized_push_listener

